### ISSUE TITLE
Multigene curator minor display edits

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#143]
- "Specific" typo Step 4 header
- Make period use match throughout heatmap option (dotplot, violin, and quadrant plots ok)
    e.g. Hierarchical clustering of observation samples. has a period while other options do not

- Move descriptions up so they are directly under each header rather than after options (e.g. 'Step 4: Groups to include' move 'Select which groups for a category...' directly under Groups to include

![Picture1](https://user-images.githubusercontent.com/28451557/148086755-3c7f7110-08a1-492d-8632-4072a248515d.png)

**Comment by adkinsrs** [comment]
I have already taken care of 1) locally.

2) Will take a lookover for consistency in periods.  I did a recent lookover for capitalization (first word vs all major words in similar grouping headers)... did this look consistent to you?

3) I had the helper text at the bottom of the input because of various UI/UX examples having it there. Your example does make a lot of sense (especially with longer sets of inputs), so I'll move them all up above the inputs.

**Comment by JPReceveur** [comment]
@adkinsrs just took another look and capitalization looks good

**Comment by adkinsrs** [comment]
Pushed out a commit for point 2 and point 3. Code is deployed on gear-devel

**Comment by JPReceveur** [comment]
Tested and all points are resolved, closing.
