### ISSUE TITLE
suggestions about comparison tool on devel (from Ronna)

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#150]
**1. The comparison tool does show the dataset title.**

![Screen Shot 2022-01-06 at 9 13 40 PM](https://user-images.githubusercontent.com/6730079/148480343-5ff76654-c71c-486b-b99a-ef56e7639d7d.png)

**2.  the selection should be displayed under the box after selecting X condition /Y condition** 
![Screen Shot 2022-01-06 at 9 15 44 PM](https://user-images.githubusercontent.com/6730079/148480513-046e0953-82a8-4ab9-bb4f-693430a8fad5.png)

**3. the default X label / Y label should display the selection of X condition/ Y condition.**

![Screen Shot 2022-01-06 at 9 19 19 PM](https://user-images.githubusercontent.com/6730079/148480767-767e5349-825e-42b9-a7e8-695d7ed52ad7.png)

**Comment by adkinsrs** [comment]
I have some thoughts on the three of these suggestions.

1. Was the comparison tool loaded from a dataset panel (does the URL have a dataset_id)? If so, then yes, I need to pre-select the dataset title in the dataset tree.  Otherwise the dataset title is already shown after the dataset is selected.

2. I personally feel this can make the side-panel look very busy, but I'll do it.  I drew inspiration from the side-panel in cellxgene, and they do not show the selection beyond what is checked or not-checked.

3. The default x-label and y-label in the plot is already the selection conditions.  I feel a better solution would be to indicate that the default label is the selection criteria if a label is not passed.  Adding the selection criteria by default in the input box would a) be redundant with point 2, and b) hinder the end-user's ability to realize this input text can be customized.

**Comment by songeric1107** [comment]
about 1.  Yes, it is loaded from a dataset panel.
![Screen Shot 2022-01-06 at 9 13 29 PM](https://user-images.githubusercontent.com/6730079/148481957-5c868786-9ead-4eeb-80dd-5767af748fed.png)
![Screen Shot 2022-01-06 at 9 13 40 PM](https://user-images.githubusercontent.com/6730079/148481962-356e3bea-e1d7-41df-8e29-d9f4b5bf5199.png)

**Comment by adkinsrs** [comment]
I have implemented each of the three bullet points.  For point 3, I make the default condition label using the JSON Stringify function, but do not that if the user selects multiple groups or categories for their condition selection, then the label can look a little verbose.

@songeric1107 and/or @JPReceveur please test on gear-devel

**Comment by JPReceveur** [comment]
1. Works as expected, no issues found
2. Agree that it makes the side panel busier but works as expected
3. Works as expected

If you try to break the columns by picking nonsense X and Y conditions you end up with something link this, which will probably be a somewhat common error if people are just playing around with groups.
<img width="1128" alt="Screen Shot 2022-01-14 at 3 32 53 PM" src="https://user-images.githubusercontent.com/28451557/149581791-0b950094-4406-4744-b3c7-5de87febc146.png">

Would it be worth changing around the text from "Please submit for help..." to something like "Please check the error message below and confirm plot selections are valid. If you need additional help, please submit for help with the following information:" ?

Just to put the idea in user's heads that they might need to changes their selections instead of going straight to telling them to submit a help message.

**Comment by adkinsrs** [comment]
Had a chat with Ronna, @songeric1107 , and @jorvis .  I am going to do the following:

* Remove the "Selected conditions" section as the "axis labels" inputs should be able to pull double-duty to show what has been selected
* Auto-populated axis label inputs will not show the condition... only group1;group2;group3 etc.
* Instructions that are initially shown on page load, will be added in a popover menu under an "Instructions" button at the top of the left section.
* Will rename some options labels to start with verbs, actions tend to make more sense to users per UI/UX standards.
* Will rename the error message that @JPReceveur describes above.

**Comment by adkinsrs** [comment]
committed  337041a which resolves the 5 issues from the previous comment.

@songeric1107 and @JPReceveur, can you check gear-devel and give further suggestions?

**Comment by adkinsrs** [comment]
3 is interesting as it shows for me locally.  I'll look into the difference.

For 5, I've noticed it there too, but have always just let it be... I figured it was extra information for the user.

**Comment by JPReceveur** [comment]
Tried it after refreshing page. If I open the help from a refreshed page (before clicking plot) I can see both the instructions and plot controls. But if I open the help after making the plot, I don't see the instructions

<img width="1047" alt="Screen Shot 2022-01-18 at 12 37 18 PM" src="https://user-images.githubusercontent.com/28451557/149989344-80fadab5-ea2a-4a81-9b1e-280c78e83264.png">

**Comment by adkinsrs** [comment]
@JPReceveur I made adjustments.  Realized that piece of HTML has a class that is hidden when the plot is created.  Resolved it so it should be good now.

**Comment by JPReceveur** [comment]
@adkinsrs Popup works for me and all other issues look resolved.

**Comment by adkinsrs** [comment]
Cool.  I will probably present on this during Wednesday's standup and if people are good with it, I'll close the ticket.
