### ISSUE TITLE
HeatMap taking very long to load

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#190]
The heatmaps from the multigene display don't seem to be loading ("loading..." for more than 5 min now).
Actually, the problem is that heatmaps won't display for only one gene whereas violin and dotplot are ok with it.

**Comment by adkinsrs** [comment]
I originally had the heatmap work if just a single gene was provided but for those cases, I had to code the heatmap differently instead of using the Dash.bio Clustergram function (which failed if there was 1 or 0 genes).  Since it was a pain to maintain two different sets of heatmap plot types/checks/conditions depending on if a single gene or multiple genes were provided, I dropped single gene support for heatmaps given this was the multigene curator.  I addressed this in https://github.com/IGS/gEAR/issues/114
 
 What is interesting is that if you pass in a single gene and click Create Plot, you should get an alert box saying you need to pass in 2 genes.  @beamilon are you not getting this box?

<img width="616" alt="Screen Shot 2022-02-01 at 2 53 09 PM" src="https://user-images.githubusercontent.com/5665914/152041117-3129b490-5a0d-4818-ba88-97ccd7a1be27.png">

**Comment by beamilon** [comment]
@adkinsrs: I was using several genes to create the heatmap. Then going back to the main gEAR, I put sox2 in the search bar to load a profile. Then I turned on the multigene option just to switch the view before adding new genes and I couldn't understand why the heatmaps were stuck in "loading..." Is it possible to change "loading..." to something like "2 or more genes are needed"?

**Comment by adkinsrs** [comment]
Ah that makes more sense.  I'll work on a fix for the main page.

**Comment by adkinsrs** [comment]
In fact I need to put an error on any plot that fails to load on that page.

**Comment by adkinsrs** [comment]
Closing this in favor of #191
