### ISSUE TITLE
HeatMap labelling improvement if feasable

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#199]
When a dataset has 3 conditions, one condition is chosen for the first category, one condition for the second category and the third condition can be implemented with the cluster colorbars. However, when cluster colobars is checked, the labels on the heatmap for conditions 1 and 2 are not displayed. Can we have the labels showing up? The example shown is for the Outer Hair Cell Response to PTS-inducing noise (PrestinCre;RiboTag;CBA mice), RiboTag RNA-seq dataset.
![image](https://user-images.githubusercontent.com/70719873/152651750-cd4feb66-e85d-4fb6-a00d-b87252cb52a2.png)

**Comment by adkinsrs** [comment]
I originally included observation labels, but I took them out after generating some heatmaps where the observation labels would very cramped against each other to the point of being unreadable.  Furthermore, excluding the labels makes it easier to show the plot better in the gene results display page. What I can do is maybe show the labels if the number of observations is under a number like 80 and hide them if above that number.  I would still hide them on the gene results display page though, since labels tend to make the heatmap pretty unreadable.

**Comment by beamilon** [comment]
The problem with the high number of observation is fixable if using the matrixplot to group replicates. This is why that would be super useful to be able to have the colorbars with the matrixplot. Is there really no way to integrate in the code the fact that the observations grouped are observations from the same condition, to be able to have the colorbars?
The problem is that a graph with no label is not meaningful.
I also like your idea of putting a limit in the number of observations to allow labels to display.

**Comment by adkinsrs** [comment]
I can write some code to add clusterbars for the categories used to split the observations within the day (though that may change since I haven't been feeling well today and yesterday).  If we need clusterbars for categories not used in the "split by" options, then that will require a bit of a rewrite in the heatmap code.

**Comment by beamilon** [comment]
No problem. I am just giving feedback every time I think of something but I realize that not everything can be fixed at the same time. If you can do it for the workshop on Friday, it is good but if you don't feel good, it will wait for you to be better.

**Comment by adkinsrs** [comment]
In any case, I pushed a commit where observation labels for all plots will show.

**Comment by adkinsrs** [comment]
Closing this ticket since the original question (labels on all observations) was addressed.
