### ISSUE TITLE
Multigene Curator - Enable clusterbars on matrixplots

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#200]
That may be naive on my part but I don't understand why creating a matrixplot needs to disable the cluster colorbars from the heatmap. In the example below, can the means for gene expression still be linked to the condition that the individual replicates were linked to? This would allow to display 3 conditions even when using the matrixplot.
![image](https://user-images.githubusercontent.com/70719873/152652502-0e607993-5b50-4861-9898-dbbd84e7c129.png)

**Comment by adkinsrs** [comment]
I originally disabled this because of the work involved (and since the name was in the observation), but it is definitely possible to add the colorbars to a matrixplot. Currently, I map to colors to the original observation labels, so I would need to do a similar mapping with the current matrixplot labels. 

For your example however, I cannot create a clusterbar for the "condition" label, since I create the matrixplot by running.a "groupby" command on the other 2 conditions, which takes the mean expression of all observations within those conditions.  The "condition" category that you want as a clusterbar is unfortunately lost through the "groupby" command.

**Comment by jorvis** [comment]
After talking through this with Shaun it became clear that, while this would be a useful improvement, it would be too much code refactoring for the current week.  Leaving this as a ticket we can add to a later Sprint after ARO.

**Comment by adkinsrs** [comment]
Going back to commenting on this issue.

I realize the context of the clusterbars in this particular dataset.  Observations at 0hr are considered "baseline" and any other timepoint is considered "noise".  The issue is that the dataset is transformed using the "groupby" method so that the mean expression can be calculated on every primary/secondary category group combination, which drops the "condition" category out of the dataframe.  Using the A1 Hackett dataset as an example, I can create a matrixplot taking the mean expression of all "condition" and "time point" category combinations, but this transformed dataframe removes the "gender" category, so clusterbars cannot be made.

I believe the issue is that the matrixplot is taking aggregating the selected categories with no consideration for replicates, and what @beamilon wants is to create a matrixplot where all replicates for each category combination are averaged out. That would solve her problem as the heatmap could now adequately generate a meaningful plot and give clusterbars the way she wants. I think this would also make sense for dotplots as well.

I think what I'll do is add an option to average out replicates (or make that a default), but this would disable the matrixplot option as the matrixplot does a "groupby" on the selected primary and secondary categories instead of sorting the data by them.

**Comment by beamilon** [comment]
That sounds good to me. The only reason I was using the matrixplot option was to average the replicates.

**Comment by adkinsrs** [comment]
After mulling it over and chatting with @songeric1107 and @beamilon, I think I will change the "matrixplot" option to do this feature, since there may be no point to the matrixplot option as is.  Since the existing "matrixplot" code is in version history, it should be easy to revive if needed.  Also, keeping the same option name will not overly break things.  Those plots should not limit observations anymore (which is what @beamilon wants), but now those displays can be edited to include clusterbars.

**Comment by adkinsrs** [comment]
<img width="1372" alt="Screen Shot 2022-02-25 at 11 58 21 AM" src="https://user-images.githubusercontent.com/5665914/155755882-4dc74bdf-0476-4747-942d-814f64b6df15.png">

Progress update.  Clusterbars now show if the replicates are aggregated.  Per @beamilon's preference the observations are combination of all categories but the labels leave out any excluded filters (in this case, "time point" groups, which still appear in clusterbars).  

My next step is to further aggregate groups down if the user only selects clusterbar categories that are not included in the filters. For this example, if the user does not want to see "time point" clusterbars, I will take the aggregate mean expression of the 4 combinations of "gender" and "condition" categories.  This would be similar to how the original matrixplot was behaving.  Does this seem fair?

**Comment by adkinsrs** [comment]
<img width="1370" alt="Screen Shot 2022-02-25 at 1 34 22 PM" src="https://user-images.githubusercontent.com/5665914/155769155-cff5a544-2abe-4e52-a0d7-bff8a1023378.png">

In response to the last paragraph of my previous comment, if a category is neither included in "filters" or "clusterbar" fields ("time point" in this example), then the category is out entirely, as the "groupby" command will calculate mean expression on the remaining category combinations.  This is to reduce redundancy in the labeling, as this goes beyond aggregation of replicates for each observation combination.

**Comment by adkinsrs** [comment]
Currently on gear-devel for testing

**Comment by adkinsrs** [comment]
@JPReceveur @Kvnrose can you take a look and give feedback?  These are largely design choices based on talks with @beamilon.  I've already had @songeric1107 take a look at this.

To summarize:
* Matrixplots will now allow the user to include clusterbars in the plot.
* The mean expression is aggregated by a union of the chosen categories to include as well as the chosen clusterbars to include.  
* This means if the user chooses all clusterbar categories, the matrixplot will take mean expression of all replicates for each group (see picture at https://github.com/IGS/gEAR/issues/200#issuecomment-1051029404).  
* However if a category is excluded and it's clusterbar option is not chosen, it will not show in the final results as the "groupby" function will aggregate it out (see pic at https://github.com/IGS/gEAR/issues/200#issuecomment-1051099322)
* Observation labels will be based on the included categories and groups specified at the top of step 3.

**Comment by JPReceveur** [comment]
Matrixplots work as expected and clusterbars look ok, having an N= above each aggregate group might be nice, but unless a user specifically asks for it, I think it looks fine as is. 

Two comments:
- If you create a plot and then decide you want to remove a group, if you just click the x to remove under step 4 and hit create plot again, it doesn’t update the groups used in the plot. To get it to reflect what you want removed (and for the sort order to reflect the removal), I had to click off and back on the category under the sort by category section. 

Was testing with the dataset : E16.5, P15, mouse, microarray, vestibular macula and cerebellum, het and hom Bronx waltzer (Banfi)
Steps: Created a plot with random genes and all groups sorted by condition -> removed bv/bv from conditions under plot specific options and hit create plot 

- Should the instructions for ‘dragging the groups to determine a specific order’ be moved under the adjust sort order header after it appears? Currently the text is present before a user would see the draggable icons so it might confuse people if they read the directions before clicking on a category, since the categories directly below the text can’t be dragged around.

**Comment by adkinsrs** [comment]
Both of those are fair points.  Currently the list sort is created on the fly when the user selects a category, but there is no event trigger to update it if the user updates the included groups.  I can also move the instructions over too... I believe I kept them to the far left due to aesthetics but I see your point there.

I was pondering how best to add a N aggregate somewhere.  Since I had not thought of a best way yet, I had not added it. I may look at some example heatmaps and see what they do.

**Comment by beamilon** [comment]
I tried with Outer Hair Cell Response to PTS-inducing noise (PrestinCre;RiboTag;CBA mice), RiboTag RNA-seq and I like it. It gives more flexibility when there are more than 2 categories.

**Comment by adkinsrs** [comment]
> * If you create a plot and then decide you want to remove a group, if you just click the x to remove under step 4 and hit create plot again, it doesn’t update the groups used in the plot. To get it to reflect what you want removed (and for the sort order to reflect the removal), I had to click off and back on the category under the sort by category section.

@JP I was not able to replicate this behavior "technically".  By that, I mean that when I plot, then remove a group, there is an initial dropdown that wants me to select another group to include.  However if I ignore that in click "Create Plot" that is not actually creating a plot, but instead deselecting the "group selection autocomplete" feature. Clicking "Create Plot" after this creates a plot with the updated groups... no messing with the sort categories needed.  

Though I do still need to implement something to auto-update the sort order groups if a group is added or removed.
