### ISSUE TITLE
sign in issues

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#215]
New people who signed in during the workshop get signed out each time they go back to the main page.

**Comment by adkinsrs** [comment]
@beamilon which page were they trying to access when they got signed out?

The process was sign-in -> new page -> back to main page, which signs them out?

**Comment by beamilon** [comment]
Yes I think that's correct. Going back to the main page from another page in gEAR logs them out

**Comment by adkinsrs** [comment]
Thanks! Fixing that will be priority 1 for me next week (since it's a bit too quick a turnaround to resolve during the workshop).  @beamilon do you know if they are clicking the "gEAR" icon to get to the front page, or are they hitting the "Back" button?  Since there are multiple ways to navigate to the main page, it would be useful to know if any specific means of navigation are causing this.

**Comment by adkinsrs** [comment]
I also wonder if this is happening after navigating away from specific pages.  @JPReceveur told me he has observed this behavior on the manual and dataset explorer pages, both of which I have not touched.

**Comment by beamilon** [comment]
@adkinsrs: I don't know if they click "gEAR" icon to get to the front page, or if they were hitting the "Back" button?

**Comment by JPReceveur** [comment]
Error message:
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at window.onload (index.1644613005866.js:254:14)

**Comment by adkinsrs** [comment]
This is the console error that I asked @JPReceveur when it replicated this issue going back to the main page.  Since I added the MutationObserver to the compare tool and the multigene curator tool, one would also expect this to show on those pages as well.  I think the difficulty is that I personally haven't been able to replicate this, so despite being up-to-date on my browser (matching the same version as @JPReceveur ), there is something preventing me from getting this console error.

**Comment by adkinsrs** [comment]
On second thought, I think commenting those out would not be the best course of action since some initial genecart/dataset/profile tree loading for a couple pages occurs after the logged in user changes from the default "user" user (logged out status) to the logged-in user.

So I need to work on ensuring the "logged in controls" load before the mutation observer loads.

/end braindump

**Comment by adkinsrs** [comment]
Fixed via #341

Currently fixed in "projectR" branch, which is currently deployed on the gear-devel server.  It will be deployed to the production server in a future update

**Comment by adkinsrs** [comment]
I was trying to avoid working on "main" since you mentioned you were going to update the servers soon.  I can mirror this commit in "main" too if necessary
