### ISSUE TITLE
Having "not applicable" instead of "No default display. Create one in the multigene curator."

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#219]
The Epiviz datasets can't have multigene displays and right now the message in the dataset window is "No default display. Create one in the multigene curator." Is it possible to have something like "Not applicable" or "Epigenetic dataset so not applicable" as a message instead for the Epiviz datasets?

**Comment by adkinsrs** [comment]
Sure.  I can get to work on this.  Can you give me an example of an epigenetic dataset so I'm not trying to fish for one?

**Comment by beamilon** [comment]
Here is one: P2, mouse, scATAC-seq, Chromatin Accessibility (Waldhaus)

**Comment by adkinsrs** [comment]
I thought about this, and I could definitely put some sort of "Not supported" tag for datasets that would normally not be able to be returned for potential curation in the multigene curator.  And it seems the reason this dataset cannot be curated in the single or multigene curators is that it has no h5ad file.  I'll probably also do a sweep to ensure datasets with no h5ads cannot be used in tools such as the "compare" tool, which gives an error when this dataset is passed in.

**Comment by adkinsrs** [comment]
Here are the two adjustments I have made (currently on gear-devel on the "genecart_frontpage" branch).

* For any dataset without an h5ad file, I hide the compare tool and curation tools, in addition to the previously hidden scRNA-Seq workbench.  This is because these tools require reading h5ad files.
<img width="1229" alt="Screen Shot 2022-02-15 at 12 52 43 PM" src="https://user-images.githubusercontent.com/5665914/154120293-21a9ed4e-0820-4413-aa88-20e8ff2f9851.png">

Working on the error message when the user switches to multigene displays now

**Comment by adkinsrs** [comment]
<img width="464" alt="Screen Shot 2022-02-15 at 2 44 29 PM" src="https://user-images.githubusercontent.com/5665914/154136998-23eeef2d-a8ed-4604-917e-10d50b762941.png">

**Comment by adkinsrs** [comment]
Code changes are committed and on the gear-devel server.  Closing ticket.
