### ISSUE TITLE
the profile name is displayed incorrectly after viewing  the selected dataset of interest

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#228]
If you search a dataset of interest and click view butter, the profile name is not the right one assigned to the dataset, which is confusing.

this dataset should belong to "Auditory/Vestibular mutants / Mouse models / Cochlea" profiles.

https://umgear.org/dataset_curator.html#/dataset/1123e546-e178-01a4-54d9-13492913c739/displays

![Screen Shot 2022-02-23 at 12 51 35 PM](https://user-images.githubusercontent.com/6730079/155378340-60ac8213-53ac-4e21-a8e3-8cf85da82d15.png)

![Screen Shot 2022-02-23 at 12 51 44 PM](https://user-images.githubusercontent.com/6730079/155378357-8b9b9e98-f94e-4621-aeb7-418bf9191109.png)

**Comment by jorvis** [comment]
I made some modifications to fix this but Shaun has also redesigned how the buttons and things look after searches are performed.  The combination of these means that the search controls now look like this after viewing a dataset directly:

![Screenshot from 2022-04-06 11-16-34](https://user-images.githubusercontent.com/330899/162020865-795ccc88-9510-4018-a2bc-c66e0df1c6f4.png)


The profile selector is removed entirely.  Since one dataset can be a part of many profiles it doesn't make sense to show any particular one.
