### ISSUE TITLE
Multigene viewer problem for 3 profiles

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#244]
I was updating some of the multigene displays and noticed a problem for all the datasets in the following 3 profiles:
- scRNA-seq - Chicken basilar papilla (Heller 2021)
- scRNA-seq - Crista, mouse (Bermingham-McDonogh)
- scRNA-seq - Chicken dying hair cells (Heller 2021)

The categories appearing don't correspond to the ones from the datasets and the icon with "loading plot options" is stuck in the loading option.
Below are examples for 2 of the datasets
I didn't have any problems with other profiles

![image](https://user-images.githubusercontent.com/70719873/157766249-2ad459a3-991c-4ce2-ba9b-f66fdc6dc1d4.png)
![image](https://user-images.githubusercontent.com/70719873/157766303-879c8fe2-8093-45bb-9a06-6cc8260f4916.png)

**Comment by adkinsrs** [comment]
I think that is probably an issue with the API call to retrieve the updated observations.  Will investigate more.

**Comment by adkinsrs** [comment]
Ok @beamilon figured out the issue.  For each of these conditions, I use the condition name to create an HTML ID for the various pieces the condition is involved in.  There is an issue with a check after the "orig.ident" condition loads because the HTML is not parsing the name properly.  I originally addressed this for a bunch of other issues but it looks like this one may have escaped.

**Comment by adkinsrs** [comment]
Committed a fix, plus I hard-coded the fix the gear-production.
