### ISSUE TITLE
Private datasets accessible in public profiles

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#259]
I was attempting to work on an issue by @beamilon and came across a private dataset in a public profile

Profile - scRNA-seq - Chicken basilar papilla (Heller 2021)
Dataset - Chicken Basilar Papilla Baseline, P7, svg,scRNA-seq (Janesick), geneID  *(others in the profile are the same)*

In this case, the datasets in this profile are owned by "curator" and when I am logged in as "Shaun Adkins", I can view single and multigene displays.  But when I click on the "multigene viewer" button to go to the curator, the page will not load the dataset (nor is it searchable) because the dataset is not public, nor shared with my user.

So the first question is if this is intended behavior?  If not, there is the potential worry that this is a backdoor way of exposing private datasets to a public environment.  @beamilon has told me she will look to see if there are other private dataset/public profile situations too.

**Comment by jorvis** [comment]
The behavior of showing all datasets in public profiles is as intended.  I believe what has happened here is that datasets which were initially private were released simply by putting them in a public profile rather than also taking the step of making the individual dataset public too.  

I'll get Ronna to verify that these are all meant to be open, and also add a warning to the dataset manager on any attempts to add a private dataset to a public profile.

**Comment by jorvis** [comment]
I have changed all of these with the following queries:

```
UPDATE dataset SET is_public = 0 WHERE is_public IS NULL;
UPDATE dataset SET is_public = 1 WHERE id IN (
  SELECT did FROM (
       SELECT d.id AS did
         FROM dataset d
              JOIN layout_members lm ON lm.dataset_id=d.id
              JOIN layout l ON lm.layout_id=l.id
        WHERE l.is_domain = 1
          AND d.is_public = 0
  ) as dats
);
```

Why the silly nested SELECTs?  [For reasons](https://stackoverflow.com/a/9843719/1368079).
