### ISSUE TITLE
move the legend to the bottom of UMAP

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#273]
Based on a response from a client, is it possible to move the legend to the bottom of UMAP plot?

![Screen Shot 2022-04-05 at 2 20 03 PM](https://user-images.githubusercontent.com/6730079/161823465-55f2137d-752b-4b18-9413-867f39ea63cc.png)

**Comment by adkinsrs** [comment]
I could spread it out over the bottom of the plot.  However, since everyone would not want a horizontal legend, it would have to be an option in the dataset curator that can be enabled and disabled.  Furthermore, this setting would have to be added to the config of existing curations that request the change, or a new curation would have to be made instead.

I am not sure that I would consider this the highest priority at the moment, given that projectR is my main working focus right now.

**Comment by songeric1107** [comment]
sure. take your time.

I think it will be good if we have an option to move the legend.

**Comment by songeric1107** [comment]
From client:

Can we please add more resolution to the violin plots and remove "cell type” (red circle).
You have a lot of white space in the violin plots. Can you expand the individual violin plots so that the data points are not so squeezed/tight
![Screen Shot 2022-04-06 at 8 28 47 AM](https://user-images.githubusercontent.com/6730079/161974728-56cf28c7-a786-4f93-9d5e-33d352bc316d.png)
?

**Comment by adkinsrs** [comment]
This last comment should be in a separate issue.  I think the violin plot would look better after using the "zoom" button

**Comment by songeric1107** [comment]
move the violin request to another ticket .  https://github.com/IGS/gEAR/issues/274

**Comment by adkinsrs** [comment]
<img width="1096" alt="Screen Shot 2022-04-08 at 3 15 38 PM" src="https://user-images.githubusercontent.com/5665914/162509438-815f9752-3c82-43a8-adee-5fca8a1be0b4.png">

I have this working now.  However when you plot by condition, the horizontal legend appears too far below the plots, so I am still figuring out the right spacing figure for that.

**Comment by adkinsrs** [comment]
Also worth noting the legend is still sorted vertically... should I resort so that it reads in the specified order when looked at horizontally?

**Comment by adkinsrs** [comment]
1. Added "plt.tight_layout" to crop out much of the whitespace around generated plot grids.  This also solved an issue where the horizontal legend for "plot by condition" was being placed too far down.
2. Horizontal plots also now read left-to-right.  This was a pain-in-the-butt to figure out how to do.

Committed and ready for merging

**Comment by JPReceveur** [comment]
- [ ] Tooltips highlighted in red below don't display any text when you hover over them.

<img width="559" alt="Screen Shot 2022-04-25 at 4 00 39 PM" src="https://user-images.githubusercontent.com/28451557/165165704-40eae9f3-aa38-4905-b67a-5cbb7ea40e63.png">

- [ ]  When testing on the dataset P1, mouse, scRNA-seq, cochlear epithelium (Kelley) (in the hearing profile) legend shows ok normally but legend disappears when legend under plot is selected (with and without skip gene plot selected).

<img width="1405" alt="Screen Shot 2022-04-25 at 4 06 59 PM" src="https://user-images.githubusercontent.com/28451557/165166515-2158976f-13cb-496b-96d1-b30fafc00b46.png">

<img width="1396" alt="Screen Shot 2022-04-25 at 4 08 47 PM" src="https://user-images.githubusercontent.com/28451557/165166766-f1496254-dad0-4c68-b0bc-51b39b937bc1.png">

**Comment by JPReceveur** [comment]
Might also be worth it to include a warning in the plot by group tooltip that higher number of groups may cause issues. Not sure how slow this will be on production but it took around 5 mins for the plots to show up for the dataset above. I accidentally added cell type here instead of in the colorize legend dropdown and was wondering why it took forever before I realized it.

**Comment by adkinsrs** [comment]
Here are the improvements I have made so far.

* added a warning for the "plot_by_group" section if the number of groups in the chosen category is 10 or more
* Modified the tooltips for checkboxes in the tsne/umap_static plots and for some other plots.  It seems vue-bootstrap has some issues adding a tooltip if the next element is not a label (I was adding to the form checkbox element). Tried to rearrange some code but that presented formatting issues. So what I resolved doing was setting the tooltip on the checkbox label itself instead of the "?" icon.

**Comment by adkinsrs** [comment]
@JPReceveur can you check these things in gear-devel to ensure they are resolved?

I also did a refactoring of the tSNE curation code.

**Comment by JPReceveur** [comment]
@adkinsrs Warning message and tooltips look ok. The legend is still disappearing when 'place legend under plot' is selected (Tested with the single cell datasets in the hearing profile).

**Comment by adkinsrs** [comment]
@JPReceveur it just occurred to me that maybe this is a scanpy/matplotlib versioning difference between my docker image and gear-devel.  Since @jorvis is going to update the package versions on gear-devel soon, I may wait a bit to see if that resolves it.

**Comment by JPReceveur** [comment]
Sounds good, I’ll make sure to test this when the packages update and will
let you know.
