### ISSUE TITLE
the front page could not display the plots being curated

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#304]
the curation plot could not show in the front page of GCID

https://gcid.umgear.org/dataset_curator.html#/dataset/c373db45-9392-6c29-f947-f353e53da71f/displays

![Screen Shot 2022-04-29 at 5 15 50 PM](https://user-images.githubusercontent.com/6730079/166070254-754caadd-85ac-4f87-9bb4-72883eabb8d4.png)
![Screen Shot 2022-04-29 at 5 15 24 PM](https://user-images.githubusercontent.com/6730079/166070261-5e50c8be-93dc-4941-b50f-c4d4d41c35cd.png)
![Screen Shot 2022-04-29 at 5 16 59 PM](https://user-images.githubusercontent.com/6730079/166070344-9951b808-947a-468b-8a15-c668afb72a34.png)

**Comment by adkinsrs** [comment]
Some of the genes from the Genbank file did not load into the database, including that one. I believe this locus tag was skipped (along with others) because they did not have a gene symbol in the genbank file (as a /gene qualifier).  The script to upload genbank to database skips genes without the gene symbol, so I'll need to modify that script if we still want those genes.

**Comment by adkinsrs** [comment]
I reuploaded the annotation db so these should show now.
