### ISSUE TITLE
More specific dataset upload errors

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#311]
@carlocolantuoni recently reported a mysterious dataset upload error that, upon checking the error logs, turned out to be a bad organism ID name in the metadata file.  This is probably a good time to improve some of the error reporting to aid users in diagnosing their upload issues.  Maybe a try/catch in the JS to propagate specific human-readable error messages from the CGI scripts.

**Comment by songeric1107** [comment]
when the file's name are wrong, you only get an error as follows, instead of showing the names of the files are incorrect, may need more specific error message

![Screen Shot 2022-05-17 at 5 29 18 PM](https://user-images.githubusercontent.com/6730079/168914892-99b0c14e-bd12-44c6-b18a-b03703b5e268.png)

**Comment by jorvis** [comment]
In general, we need to javascript-validate any column length limitations on the form that match with schema limitations.

**Comment by adkinsrs** [comment]
@jorvis I assume this is safe to close as you are revising the uploader for ui-v2?  If it is safe to close, I'll let you do the honors
