### ISSUE TITLE
Missing functional annotation (GO) - follow-up

### ISSUE THREAD

**Issue by eboileau** [IGS/gEAR#354]
Dear @adkinsrs 

Thanks for your quick reply, but it looks like [this issue](https://github.com/IGS/gEAR/issues/352) is not solved by https://github.com/IGS/gEAR/commit/c3370098ee479fe68f93d2d56cc71cdb7e143243.

In fact, `projection_source` appears to be undefined at this stage, so the conditional is never satisfied.
What I meant was I could only make it work by removing the conditional, and just leave

```
annotation_panel.annotation = search_results[gene_sym];
annotation_panel.autoselect_organism();
```

This is obviously only a quick fix, as I have not yet figured out how this projectR is integrated, _i.e._ `projection_source` should be defined at some point...

In addition, currently only the first organism is shown, and the others are always _inactivated_.
I think this commit https://github.com/IGS/gEAR/commit/fd53e7e9c385c98c236ded354a2f11fc86feda20 broke it. Reverting back to the old definition temporarily fixes it.

**Comment by adkinsrs** [comment]
@eboileau thanks for the heads up.  Yesterday I took a few more steps to try and clean up some of the broken projectR code on the "main" branch.  As of the latest commit, `projection_source` is only defined in the $('#projection_search_form').submit() event, which should never occur on main, as the projection tab and the "search" button are commented out in the HTML.  The "projection_source" is the ID of a projection pattern or weighted genecart obtained from the projection JSTree (currently commented out on "main")

Because this code will never be executed on main, the "projection" variable near the top of index.js will never have the opportunity to be set to "true" and so the code at https://github.com/IGS/gEAR/blob/c3370098ee479fe68f93d2d56cc71cdb7e143243/www/js/index.js#L790-L793 will always execute.

**Comment by adkinsrs** [comment]
I just realized at it's current commit, I did not move over the "functional annotation hidden for multigene searches and projections" box, and so that should be pushed in a future commit (today).  Currently, in my tests, annotations successfully show in single-gene searches, but in multigene searches, the annotations are empty (when in reality the "not supported" box should be shown).

**Comment by jorvis** [comment]
@eboileau - Just as a sanity check, did you actually happen to load any annotation into your local db?  I realize that part of instantiating a new instance may not be well (or at all) documented.

**Comment by eboileau** [comment]
@jorvis Thanks, yes, indeed I don't think it is documented. I'm actually going through this now, I've done a minimal implementation in my Ansible install here: https://github.com/eboileau/gear_lamp/blob/main/roles/db/configure/tasks/dump_db.yaml. I am mostly using your scripts under gEAR/bin, with minor modifications. Running `db-config` will create the DB, download the annotations, and load them to the respective DB tables.

**Comment by jorvis** [comment]
OK, great.  And functional annotations now restored on the umgear.org site

**Comment by jorvis** [comment]
Please re-open if there's anything left to do here.
