### ISSUE TITLE
Many multigene displays show "There was an error drawing the plot."

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#360]
@adkinsrs Everything was working yesterday but now many datasets are showing the above error message when switching to multigene view.
Here is a URL link as an example
https://umgear.org/index.html?multigene_plots=1&layout_id=fee360e8&gene_symbol_exact_match=0&gene_symbol=pou4f1,pou4f3,pou4f2

**Comment by adkinsrs** [comment]
`ValueError: items in new_categories are not the same as in old categories`

Seems there is an issue with reordering gene symbols in the dataframe.  These two failed plots were dotplots... have you seen this with any other plot types?

**Comment by beamilon** [comment]
I am not sure but here is another example with several showing the same message, one of the dotplot is displaying correctly.

**Comment by adkinsrs** [comment]
Think I found the issue.

Trying to reorder the genes based on the order of the passed in gene symbols. The dataset genes use an upper-case P, but the searched genes have lowercase p. The dataframe cannot reorder because it is not case-insensitive.

So I need to convert the searched genes into the format that matches the casing of the dataset genes.

**Comment by adkinsrs** [comment]
Am committing a fix, and edited the production server to also have the fix, in case @jorvis does not want to pull "main" onto the server.

Seems the error was present for both dotplots and multigene violin plots.

**Comment by beamilon** [comment]
Working :)

**Comment by adkinsrs** [comment]
a7b59d887f8fe49147ffed90dbdf6b704e541ff7 resolves it
