### ISSUE TITLE
add a category in the metadata sheet to tag whether the dataset is using the raw value or normalized values

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#372]
Should we add another category in the metadata sheet to tag whether the dataset is the raw value or normalized value? 

this is important for single-cell datasets. For all the log normalized datasets, using the single-cell workbench to re-log transform or renormalize the dataset will not be appropriate.   If we see the "normalize" tag in the metadata sheet, we should disable the function to use the workbench from scratch or provide a suggestion that they use the primary-analysis function only.

**Comment by JPReceveur** [comment]
Yes this change is part of the updated metadata template efforts that are taking place related to #193 and #216.  In the updated metadata template the plan is there will be two categories related to this 1. whether data is raw, log2, log10 and 2. What normalization method is used (e.g. TPM,FPKM etc).  I'll close this as duplicate for now since the whole template change is already in progress.
