### ISSUE TITLE
Mr.

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#376]
**From:** Dennis Derstroff

**Email:** dderstro2020@gmail.com

**Server IP:** 10.142.0.16

**Msg:** Dear sir and madam,

i would like to ask whether there is a function to search for highly expressed genes specifically in choosen cell types. There are these preset gene charts but it offers only a limited number of options. 

Thank you!

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
Responding to this user, with screenshots, now.

**Comment by jorvis** [comment]
Response:

Depending on the content of the dataset you are interested in, yes.  The [comparison tool](https://umgear.org/compare_datasets.html) allows you to choose any dataset and any conditions within that dataset (such as cell type) and perform an X-Y scatter.  There are quite a lot of options here, including filtering based on log fold change, highlighting specific genes in the plot, statistical tests, etc.  You can then hover over the interactive graphics to check which genes are differentially expressed and even select them to save as a gene cart, which can be used elsewhere on the site.
You can also check out the [manual](https://umgear.org/manual.html), then click the "Compare tool" tab on the left for slides and a walk-through video.  The tool has been updated with more features since the video was created, but the overall flow is still similar.

I hope this helps.

Joshua

![Screenshot from 2022-07-22 09-57-01](https://user-images.githubusercontent.com/330899/180467382-86890120-7d78-4df2-80a0-24b3e988d38b.png)
