### ISSUE TITLE
Adding color choices to static UMAP displays

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#379]
The dynamic UMAP option in the curation page allows users to choose legend colors. However, that same option is not available for a static UMAP. Can that option be added so the right plot on a static UMAP can be colored according to the user's preference?

User also asked about adding the ability to paste Hex codes into the input box when choosing colors. Currently Hex codes can be typed in but not pasted.

Dynamic UMAP

<img width="1186" alt="Screen Shot 2022-07-25 at 8 34 21 AM" src="https://user-images.githubusercontent.com/28451557/180778619-dbe69b80-2389-4e31-b1ae-1d245f7e489b.png">

Static UMAP
<img width="1581" alt="Screen Shot 2022-07-25 at 8 36 40 AM" src="https://user-images.githubusercontent.com/28451557/180778863-13407a7c-1ab1-42f7-aee9-eaf23ef58280.png">

**Comment by adkinsrs** [comment]
Definitely possible to do this, but since the code to render the static tSNE options differs greatly from the dynamic tSNE options, it could take a bit of finagling to ensure this works.

One thing the user can also do is add an observation column in their uploaded data where the column name is <observation>_colors and the values are the hexcodes.

**Comment by adkinsrs** [comment]
This is present in v2. Closing
