### ISSUE TITLE
File size limit

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#506]
**From:** Yoshi Ueda

**Email:** yosueda@iu.edu

**Server IP:** 10.142.0.16

**Msg:** Is there a file size limit to upload data to gEAR?
I'm uploading our scRNA-seq data, but it has been posed by errors. I'm wondering if it is because of the file size of "upload.tar.gz" (~200 MB) containing "expression.tab" (~5 GB), "genes.tab" (~500 KB), and "observation.tab" (~10 MB).

I'd be glad if someone could help me.

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
Checking the logs now.  There is a file size limit (2GB) but that is **before** extraction of the tarball, not after.

**Comment by jorvis** [comment]
Yoshi - I've sent you an e-mail to track this ticket.  I don't see any errors in the logs around this time.  Could you please either e-mail me to share a path where I can download and try uploading your dataset to gEAR myself?  I'll change the ownership to you after, of course.

**Comment by Ystm-U** [comment]
Thank you so much for your prompt answer, @jorvis. I sent you directly to your email address on Feb. 15. I think the attempts were on Feb. 13-15.
I'll send you again to share my file soon.

**Comment by jorvis** [comment]
From looking into these files the observations.tab and genes.tab files seem well-formed.  The expression.tab file, though, has issues.  

The first line which should contain all the columns which correspond to the observations is instead just one super long string, in quotes, like this:

`"ensembl_ID-AAACCCAAGAAACTGT-1_1_1-AAACCCAAGAAGGCTC-1-AAACCCAAGATTGACA-1_2-AAACCCAAGCATGAAT-1_1_1-AAACCCAAGCTAG ....`

Then, the subsequent lines are also in quotes for some reason, and the first column is a quoted integer rather than the ensembl ID it should be.

```
$ head -n 2 expression.tab | tail -n 1 | cut -f 1-5
"1" "ENSG00000121410	0	0	0	0.693147180559945
```

This file is initially just read by pandas like this, and it is what is reporting the error passed to the interface.

`exp = pd.read_table(filepath, sep='\t', index_col=0, header=0)`

If you can fix the expression.tab file we can try again.

**Comment by Ystm-U** [comment]
I figured out the problem of my previous dataset. I mistakenly automatically replaced "\" with "/" when I copy/pasted the file Path in R. It changed the code below and made a mess.

`write.table(obs, paste0(Path, "observations.tab"), sep = "\t", quote =  FALSE, row.names = FALSE)
write.table(genes_to_use, paste0(Path, "genes.tab"), sep = "\t", quote =  FALSE, row.names = FALSE)
write.table(count, paste0(Path, "expression.tab"), sep = "\t", quote =  FALSE, row.names = FALSE, col.names = TRUE)`

So, now the datasets should have an appropriate shape, but I still get the error 
"Unable to open file for validation. Please try uploading the file again."

**Comment by jorvis** [comment]
@Ystm-U  I have converted your data file and can place it for you, making you the owner.  But the last thing I need is the metadata sheet you were going to use.  It could either be attached here or e-mailed to me.

**Comment by Ystm-U** [comment]
Thanks, @jorvis. I'll email you the metadata soon.

**Comment by jorvis** [comment]
I have loaded this dataset and sent the links/info to the user.
