### ISSUE TITLE
Resources are busy. Please try again in a few seconds.

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#514]
@jorvis
@adkinsrs 
I noticed few days ago that every so often, I get the message "Resources are busy. Please try again in a few seconds." instead of the display. It's not always the same dataset. Copied is also the messages from the console.
![image](https://user-images.githubusercontent.com/70719873/227016898-aee422be-65f2-43d4-850e-3ba75ef25c29.png)
![image](https://user-images.githubusercontent.com/70719873/227017073-642afc62-99d5-451f-9a7e-74cab74a8e13.png)

**Comment by adkinsrs** [comment]
That typically happens when there are too many concurrent requests to the server and it drops a plotting request (or projection, etc). if you refresh the plot should appear but this can be mitigated on our end by adjusting the apache server config.
________________________________
From: beamilon ***@***.***>
Sent: Wednesday, March 22, 2023 3:37 PM
To: IGS/gEAR ***@***.***>
Cc: Adkins, Ricky (Shaun) ***@***.***>; Mention ***@***.***>
Subject: [IGS/gEAR] Resources are busy. Please try again in a few seconds. (Issue #514)


@jorvis<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjorvis&data=05%7C01%7Csadkins%40som.umaryland.edu%7Ce0654a800ac349d6eaf908db2b0ce3ef%7C717009a620de461a88940312a395cac9%7C0%7C0%7C638151106601540946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=47EYuB4UwmjI6QNxfzGj4DIG52YTdmBcZ6CZqiDY2Xg%3D&reserved=0>
@adkinsrs<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadkinsrs&data=05%7C01%7Csadkins%40som.umaryland.edu%7Ce0654a800ac349d6eaf908db2b0ce3ef%7C717009a620de461a88940312a395cac9%7C0%7C0%7C638151106601540946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U6vqDZ1gPV1dkV%2FHg%2BqZNWL18lRFEM1CDCcMstI4jy8%3D&reserved=0>
I noticed few days ago that every so often, I get the message "Resources are busy. Please try again in a few seconds." instead of the display. It's not always the same dataset. Copied is also the messages from the console.
[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F70719873%2F227016898-aee422be-65f2-43d4-850e-3ba75ef25c29.png&data=05%7C01%7Csadkins%40som.umaryland.edu%7Ce0654a800ac349d6eaf908db2b0ce3ef%7C717009a620de461a88940312a395cac9%7C0%7C0%7C638151106601540946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=79SUgBkaMxqOGPXX77MRNvrp9dCQJd%2Fji5xQ%2FwIqOXQ%3D&reserved=0>
[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F70719873%2F227017073-642afc62-99d5-451f-9a7e-74cab74a8e13.png&data=05%7C01%7Csadkins%40som.umaryland.edu%7Ce0654a800ac349d6eaf908db2b0ce3ef%7C717009a620de461a88940312a395cac9%7C0%7C0%7C638151106601540946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vAayNevFDG8FySw8wM2D4M7iiuFP3dYu5fPf5plAI8U%3D&reserved=0>

**Comment by adkinsrs** [comment]
I should also say this error used to say "there was an error drawing the plot" in many occasions where the resource was actually busy


------------------------------------------------------
Ricky "Shaun" Adkins
Bioinformatics Software Engineer II
Institute for Genome Sciences
University of Maryland, School of Medicine
Phone (410) 706-6766
________________________________

**Comment by beamilon** [comment]
I actually had to go in the display to pick another one. I had to modify the dataset in curator for the lab to see my analyses so I may have deleted the display that I had on my account. Anyway, it's all good.
