### ISSUE TITLE
Resolution issue for uMAP/tsne in gEAR 2.0

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#705]
Looking at the default hearing profile it appears the text resolution of the umap/tsne plots is distorting, which appears to be most apparent in the plotting label and the axes.  

New gEAR version

![Screenshot 2024-05-29 at 1 21 06 PM](https://github.com/IGS/gEAR/assets/32070437/966b2b69-8883-43aa-8e83-873e3a3fcef3)
![Screenshot 2024-05-29 at 1 21 14 PM](https://github.com/IGS/gEAR/assets/32070437/a9652123-2b46-4c71-8f4d-f9f150083f9f)

Previous gEAR version

![Screenshot 2024-05-29 at 1 21 26 PM](https://github.com/IGS/gEAR/assets/32070437/a7cff70e-0a54-4daf-bb63-b07d4b71b524)
![Screenshot 2024-05-29 at 1 21 32 PM](https://github.com/IGS/gEAR/assets/32070437/520021b2-40bb-42a2-baa2-502bcd0b5fc6)

**Comment by adkinsrs** [comment]
This was discussed in the "Ronna's Lab workshop" on 7/3/24

**Comment by adkinsrs** [comment]
<img width="1768" alt="Screenshot 2024-07-04 at 3 41 45 PM" src="https://github.com/IGS/gEAR/assets/5665914/855f966f-bd35-4add-bc40-f305b0c17c87">

I changed the figure ratio "height" down from 4 to 1, which yields the tSNE above.

Couple of observations:
* More spacing in between plots, and the boxes are slightly smaller
* Expanding the display yields the exact same plot rather than a zoomed in one.  This is not the case for the original gEAR figsize ratio for 2 subplots (13w x 4h). A way around this could be to generate a "zoomed in" plot with double or triple the height (the width may have to be adjusted), and return that bytestring strictly for the zoomed-in plot. Kind of against it though since that's more data being returned to the client.

**Comment by adkinsrs** [comment]
<img width="1768" alt="Screenshot 2024-07-04 at 4 16 45 PM" src="https://github.com/IGS/gEAR/assets/5665914/e9d7a0af-5e76-4f1e-96a6-ea1d5c6db75a">

Image with figsize height set to 2. There is some minor distortion in the labels but the zoomed display generates the correct proportioned view with respect to labels. Ultimately, the image is being skewed to fit the dataset tile container on the page.

@DanLesperance I pushed this to gear-devel. If it looks fine, feel free to close.  If you'd rather use the image from the previous comment (where I'd have to write extra code to generated a separate "zoomed" version, just let me know

**Comment by beamilon** [comment]
The UMAP/tSNE in several datasets are still stretched.
![image](https://github.com/user-attachments/assets/1609369b-02a2-45af-8bdc-0e3b60bfd0f8)
![image](https://github.com/user-attachments/assets/234ba071-4bdc-4756-a24f-b9ad37461721)

**Comment by adkinsrs** [comment]
Besides @jorvis "aspect ratio" preservation fix, we need to set the figure aspect ratio for matplotlib to plot #or on the server-side call

**Comment by adkinsrs** [comment]
I don't feel like copy/pasting the conversation from Slack to here so here is a link to the slack conversation -> https://igsifx.slack.com/archives/C06C4M1JAMC/p1722449466360989

**Comment by adkinsrs** [comment]
Closing this for now.  The resolution issue is going to be touch-and-go but I implemented a formula that adjusts figure aspect ratios, based on a) number of plots wide, b) number of plots high, c) display tile width, and d) display tile height.
