### ISSUE TITLE
gEAR staging: account creation/ profile update bugs

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#772]
- [x] Went through the account creation and input IGS as institute and selected both color blind mode and to receive gEAR updates. When I look at my profile in the profile viewer, those checkboxes are not selected. I would expect it to show what settings I had selected previously.
- [x]  If I try to update my information in the profile it results in an error and the update profile button spinning indefinitely . Steps: log in to account, open user profile, put a new institution or check one of the two checkboxes and hit 'update profile'

<img width="735" alt="Screenshot 2024-07-19 at 10 40 08 AM" src="https://github.com/user-attachments/assets/83c8b84d-4f8d-4a76-8426-4e3755fa0599">

**Comment by jorvis** [comment]
When I'm done with this do you want me to delete that account so that you can create it again for testing?

**Comment by JPReceveur** [comment]
Yes please, thanks

**Comment by jorvis** [comment]
There were a few issues here but I've tested it myself on staging with a new account and deleted your test account (above) @JPReceveur so you can try it again.  Part of the issue is a battle with the browser to not try to auto-fill the change-password feature, which I think was also happening to you above.

Please try again and re-open if there are still issues.
