### ISSUE TITLE
Tag list on comment page not styled properly

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#8]
When you get auto-suggest completions for the tag list on the comment page they're being rendered in an overlayed div with no background color or anything else.  See image:

![Screenshot from 2021-06-29 12-20-06](https://user-images.githubusercontent.com/330899/123840942-9c302780-d8d4-11eb-929e-5c3f9d43a678.png)

**Comment by adkinsrs** [comment]
I believe the issue lies in that bootstrap-tokenized only supports Bootstrap 3 (according to the Github page README) and we are using Bootstrap 4 on our projects.  Since this developer has posted they are no longer maintaining this project, I will switch this over to using Select2, which I used in the multigene curator for the same thing

**Comment by adkinsrs** [comment]
Committed 79b24e3
