### ISSUE TITLE
Dataset collections on dataset page take a while to load

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#801]
The dataset collection menu on dataset explorer still takes some time to load and if you switch to list view compact or list view expanded before the collections load, once they load it will force you back to table view

![Screenshot 2024-07-22 at 10 19 35 AM](https://github.com/user-attachments/assets/8b8bc13d-15fe-49f2-843b-1d0078b262ae)

![Screenshot 2024-07-22 at 10 19 54 AM](https://github.com/user-attachments/assets/caf93a4a-9766-4e53-a7ab-0db7c48d5b56)

**Comment by adkinsrs** [comment]
@JPReceveur and I discussed this on Friday.  It's because I need to include the layout display members when retrieving collections. Originally the loading of datasets wouldn't even happen until all dataset collection info was ready, but I worked around that. Eventually I need to rewrite to only retrieve members when a dataset collection is selected.

**Comment by adkinsrs** [comment]
Going back to table view relates to #806, which I will explain there.

**Comment by adkinsrs** [comment]
Made some adjustments with the last commit. Previous view should be restored after a search. Updating a dataset collection (including the initial pull of collections) will not auto-select table mode. Furthermore, changing dataset collections will only update the dataset list search if the "Show only selected collection datasets." toggle is on.

**Comment by jorvis** [comment]
I think the issue remaining here is simply that the dataset collection widget takes a long time to load, and it's because it's being called here with_members=1.  The only time we actually need the members of each collection is when the user selects a collection (whether to see members, edit layout, etc.)  Could we perhaps lazy load that individual collection's members as needed?  Then the rest of it would speed up.

**Comment by adkinsrs** [comment]
Correct. However, I will need to edit the "select collection" server-side call to retrieve the displays and generate the layout arrangement tool instead of doing this in the generic "update dataset collections" callback it is currently in

**Comment by adkinsrs** [comment]
Going to work on this today

**Comment by adkinsrs** [comment]
@DanLesperance @JPReceveur  if you want to test this change, feel free.

**Comment by DanLesperance** [comment]
Clicking around things seem significantly faster and cleaner.  One issue I've noticed is creating a new Dataset Collection it seems the collection doesn't initially belong to me?  Ie. I don't have the options I would expect (delete, rename, rename permalink etc...).  If I reload the page however the options appear

![Screenshot 2024-07-25 at 2 05 42 PM](https://github.com/user-attachments/assets/dc5fe4aa-eeff-42a5-96a1-4304f8756df8)

![Screenshot 2024-07-25 at 2 06 50 PM](https://github.com/user-attachments/assets/2cd88ce1-b187-4b35-9820-dd1b49438f27)

**Comment by adkinsrs** [comment]
Ah ok... I can fix that.  Just need to add an extra callback to the collection creation/deletion steps

**Comment by adkinsrs** [comment]
Turns out after confirming, the code would update the dataset collections using the default share ID, triggering a "select collection" callback race condition with the new collection "select" callback, but since you don't own the default Hearing profile, it would hide the controls.

So I fixed that, and also set it that adding, renaming, or deleting a collection would update the "user" list of datasets within the selector.  Worth noting that in all 3 of these (particulary the "delete" activity), the "user" category will remain the active category.
