### ISSUE TITLE
gEAR staging: deleting a gene list moves you to table view

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#806]
In the gene list manager, if you delete a gene cart, from either the list or expanded list view, you get moved back to the table view.

Not a huge issue but annoying if you're deleting multiple carts at the same time since theres no way to delete from the table view so you have to click back to another view after each deletion. I assume its the same with datasets but didn't delete any to check.

<img width="1617" alt="Screenshot 2024-07-22 at 11 32 50 AM" src="https://github.com/user-attachments/assets/95f33c97-7313-4899-9c72-d6f0e8031e6e">

**Comment by adkinsrs** [comment]
This response also applies to datasets.

Whenever an update of the gene lists or the datasets is needed, I intentionally set it back to table-view.  The reason was that the initial view was table-view and wanted it that way for consistency.  Also before this change, I had observed that if a search happened while in expanded view, the re-rendering of the lists would forget if boxes were expanded or not.

Ultimately I need to come up with a more elegant solution.  For now, I'm just going to remove the "force table view" setting.

**Comment by adkinsrs** [comment]
Made some adjustments with the last commit. Previous view should be restored after a search
