### ISSUE TITLE
Staging gEAR-Wrong message for Epiviz datasets

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#823]
@adkinsrs @JPReceveur 
Epiviz datasets are showing up with the message below. The message should be change to one explaining that Epiviz is not yet implemented in this version (or something similar if the reason is different.
![image](https://github.com/user-attachments/assets/3798d9d8-6c45-4ea0-8049-09ba8dedc658)

**Comment by adkinsrs** [comment]
I did push a commit to add a direct message if an Epiviz display is selected that it is not implemented.  However in this case, The reason why ortholog checking failed was because there was no h5ad file found for the dataset (which I confirmed on the staging site). @jorvis just reminded me that I can check for the dataset type, which is "epiviz" and handle these situations a bit differently.

**Comment by adkinsrs** [comment]
Pushed commit to address this and pulled to staging
