### ISSUE TITLE
previous profile links don't direct to the correct profile/page

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#851]
Previous profile links that would direct to specific genes/dataset collections now open the my workspace dashboard, for a second show the correct dataset in the dataset collection menu, but then changes to whatever the default is

Link to dataset collection
https://umgear.org/index.html?multigene_plots=0&layout_id=b1127130&gene_symbol_exact_match=1&gene_symbol=SOX10

Below screen capture shows an example, see how the dataset changes on MyWorkSpace Dashboard

https://github.com/user-attachments/assets/a46d414b-0ab7-4bec-a1b9-4347a762f0fe

**Comment by jorvis** [comment]
Dan -

Where are you getting URLs like that one from?  It should have 'expression.html' in it rather than 'index.html', and our permalinks all point to the 'p' redirector like:

umgear.org/p?l= .....

**Comment by DanLesperance** [comment]
They seem to be ones copied from the url bar, these were in emails I had previously.  Changing to expression.html seems to work.  I think index.html was grabbed during the previous iteration of gEAR though.

**Comment by jorvis** [comment]
OK, I'm sure you're not the only one to have this happen.  I might add something that if redirector params are detected it switches the URL to expression automatically and passes the same set.  @adkinsrs thoughts?

**Comment by adkinsrs** [comment]
It should already be directed to "expression.html" in the "p" script, unless you are referring to something else.

**Comment by jorvis** [comment]
Something else.  This is from when people manually copied v1 gEAR URLs which point to index.html rather than expression.html.

**Comment by adkinsrs** [comment]
So I see it is two solutions, and I think you are opting for the first of these.

1) check if the "index.html" url has a parameter that would be parsed in expression.html, then redirect if encountered.
2) do not redirect, and instead use the URL parameters to populate the gene(s), collection, etc. on the index.html page, then trigger a search.

I imagine the first solution is definitely preferred since 2 requires extra code on index.js to handle each parameter (and you described the first solution already)
