### ISSUE TITLE
Dataset Explorer: No way to add a dataset to a collection when view is tabular

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#895]
This came up in the Jax demo just now.  The default view is tabular, and the users created a new (empty) collection, then searched for datasets to add to their new collection.  But the default tabular view doesn't have the buttons to add/remove datasets and it isn't clear that you have to go to at least the middle expanded view mode to get these buttons.

**Comment by adkinsrs** [comment]
Given how much space the tabular/table view takes up, it is not really easy to add "quick action" buttons to it (same for gene lists manager page). I think a better solution would either be to have some clear indication that you have to go to the "list view - compact" button to do these things, or add a dropdown with the quick actions into the first column cells (or make a new cell)

**Comment by adkinsrs** [comment]
Another thing to potentially do, is to default the user to the "list view - compact" when a dataset collection is either selected or created.  However, this would probably be a repeat of #806 in terms of unwanted behavior (different view though)

**Comment by jorvis** [comment]
I feel like it could work to add a column to the tabular view with just the + / - controls when the profile selected is one of the users' own.

**Comment by adkinsrs** [comment]
<img width="1766" alt="Screenshot 2024-09-22 at 11 04 06 PM" src="https://github.com/user-attachments/assets/8adcad92-d3df-4278-8547-8ae79061a8a4">

I think that would work fine if the left navbar is collapsed, but I worry that it could look cramped depending on the browser width.  However, it may be a non-factor since the table columns are auto-sized.  I'll look into adding them.

**Comment by jorvis** [comment]
We could also look into making the Visibility icons rather than a column.

**Comment by adkinsrs** [comment]
<img width="1766" alt="Screenshot 2024-09-23 at 9 13 14 AM" src="https://github.com/user-attachments/assets/8639da77-1ddc-4bd1-aae8-caf497fea8cc">

Here's what I did. The icon on the other views is outlined dark instead of solid dark, but I didn't think an outline in a table would look good.  Clicking the icon will bring up the "add/remove displays modal" just like with the other view.

**Comment by jorvis** [comment]
That works.  I'd just suggest making it a + symbol if it's not in the current collection and a - symbol if it is.  and disabling them entirely if the user doesn't own the collection.

**Comment by adkinsrs** [comment]
Already tested for cases if the user owns the collection or not.  Keep in mind, we are adding and removing displays for a collection, not datasets, so the combo +/- is consistent with that behavior
