### ISSUE TITLE
Data download ?

### ISSUE THREAD

**Issue by Crazzy-Rabbit** [IGS/gEAR#942]
Hi,
I was wondering if there was a way to download/access the raw dataset or even Seurat object create from finding the top variable features.  I was looking at "scRNA-seq—P8, P12, P20 mouse cochleae (Michalski, 2023)” and “snRNA-seq—P8 mouse cochleae (Michalski, 2023)", and I find an option to download, but there was no response. Would I have to get author permission or may I download the data from gEAR?
![image](https://github.com/user-attachments/assets/5e3f04ac-909d-4ef2-b5a6-0b15d6cb746c)

Sincerely,
lulu

**Comment by Crazzy-Rabbit** [comment]
So, how to download this data ? Because I  found that the authors claim that these data are available from here. 
![image](https://github.com/user-attachments/assets/23dcd92e-d118-4052-8c80-ceb39208b0c2)

**Comment by jorvis** [comment]
Thanks for the ping.  So the download link there is definitely broken but in the meantime there is a work around for any dataset you can't get.  Instead of using that download link, click the "View in Expression Viewer" button on the left:

![step1](https://github.com/user-attachments/assets/58a1ba65-9634-4578-a138-91a8519308fe)

This will load that dataset in the expression viewer.  Search for any gene to display results, then in the database box click the menu in the upper right to show the controls for that dataset.  Among them, you'll see download links and I just tested that these work.

![step2](https://github.com/user-attachments/assets/a77dd913-f046-4001-9b1d-90e92aab6099)

**Comment by jorvis** [comment]
@adkinsrs I confirmed that nothing happens when you click the download link here in the dataset explorer.  No error in the console, etc.

**Comment by adkinsrs** [comment]
CGI script is returning 200 but nothing is happening.  I'll look into this as I work on my fixes for #939.

**Comment by adkinsrs** [comment]
Interestingly enough I can download "scRNAseq, Atoh1+Ikzf2 overexpression in adult supporting cells, published UMAP (Liu, 2021)" on the Dataset Explorer at umgear.org just fine, so it may be an edge-case with this particular dataset or a category of datasets

**Comment by adkinsrs** [comment]
So I left my browser running and the Michalski dataset did start downloading after 2 minutes of waiting.  It was a 4Gb dataset and actually crashed my browser tab.

So things that need to be addressed:
* Put a file size indicator somewhere, either on the dataset info or in the Download tooltip
* Put in a "loading state" indicator
* See if the download CGI script can be optimized better

Maybe as a future to-do we can set up some SCP command that can be shown to the user.  This would be much more applicable if we ever fully embrace moving all datasets into GCP buckets or GCP block storage.

**Comment by jorvis** [comment]
Here scp isn't even necessary, as a wget command would easily do it.  The problem is most users wouldn't necessarily be comfortable dropping to the command line.

**Comment by Crazzy-Rabbit** [comment]
Thanks for your reply! The issue has been resolved when I click the "View in Expression Viewer" button to download data.

**Comment by jorvis** [comment]
@adkinsrs - It works immediately in the expression viewer.  Can both pages use the same method?

**Comment by adkinsrs** [comment]
They both already use the same command and CGI script. The difference is how the response is processed.  I already created the "hotfix-942" branch with a fix that chunks the download while writing to buffer that should resolve some issues but I have yet to test it out yet.

**Comment by adkinsrs** [comment]
> Here scp isn't even necessary, as a wget command would easily do it. The problem is most users wouldn't necessarily be comfortable dropping to the command line.

The SCP/WGET command was more a suggestion when we start getting huge spatial datasets.  For example, one of the 10X Genomics example Xenium datasets I looked at was 41Gb. It does not matter in gEAR currently, but I am concerned with attempting to download such a large dataset through our current methods should we eventually get datasets of that size.

**Comment by adkinsrs** [comment]
Looking at the code more now.  The download works more natively in the gene expression search page because the HTML element controlling the download is an `<a>` tag which can take CGI script URL as the "href" attribute. 

The dataset explorer instead has a `<button>` which does not allow for "href" attribute.  The general approach is to create an event listener on the button, which creates a hidden `<a>` element that gets the href attribute.  What I had done previously is to save the CGI script output to a JS Blob object (like the solution here -  https://stackoverflow.com/questions/19327749/javascript-blob-filename-without-link), create the object URL and assign a downloadable name.  But since we the CGI script itself controls the return type and we know it's going to be the H5AD file some of this process is not necessary. So I'm going to do a commit on "feature-939" that will address this.
